# Generated by Django 5.1.4 on 2025-01-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_clothingitem_price_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='jauners',
            field=models.CharField(choices=[('NEWS_SALES', 'News & Sales'), ('CLOTHING', 'Clothing'), ('SHOES', 'Shoes'), ('ACCESSORIES', 'Accessories'), ('BAGS', 'Bags'), ('JEWELRY', 'Jewelry'), ('BRANDS', 'Brands'), ('ALL_WOMEN', "All Women's"), ('SUMMER', "Summer Women's"), ('POOL_PARTY', 'Pool Party'), ('STYLISH_DRESSES', 'Stylish Dresses'), ('SUMMER_PARTY', 'Summer Party'), ('SPORTY', 'Sporty'), ('AESTHETICS', 'Aesthetics')], default='CLOTHING', max_length=20, verbose_name='Jauners'),
            preserve_default=False,
        ),
    ]
