# Generated by Django 5.1.4 on 2025-01-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_rasor_pay_model_id_cart_rasor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
